### ISSUE TITLE
Python3: AttributeError: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by danaki** [ixc/django-polymorphic-auth#5]
I get an exception during migration:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/yuri/anaconda2/envs/sputnik/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/yuri/anaconda2/envs/sputnik/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/yuri/anaconda2/envs/sputnik/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/yuri/anaconda2/envs/sputnik/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/yuri/anaconda2/envs/sputnik/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    emit_post_migrate_signal(self.verbosity, self.interactive, connection.alias)
  File "/Users/yuri/anaconda2/envs/sputnik/lib/python3.5/site-packages/django/core/management/sql.py", line 50, in emit_post_migrate_signal
    using=db)
  File "/Users/yuri/anaconda2/envs/sputnik/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/yuri/work/sputnik/src/django-polymorphic-auth/polymorphic_auth/apps.py", line 29, in create_users
    create(name, email, fields)
  File "/Users/yuri/work/sputnik/src/django-polymorphic-auth/polymorphic_auth/apps.py", line 24, in create
    User.try_create(**fields)
  File "/Users/yuri/work/sputnik/src/django-polymorphic-auth/polymorphic_auth/models.py", line 134, in try_create
    return super(NameMethodsMixin, cls).try_create(**kwargs)
  File "/Users/yuri/work/sputnik/src/django-polymorphic-auth/polymorphic_auth/models.py", line 261, in try_create
    for key, value in kwargs.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

From http://stackoverflow.com/questions/30418481/error-dict-object-has-no-attribute-iteritems-when-trying-to-use-networkx seems that

> iteritems() was removed in python3, so you can't use this method anymore.

**Comment by sjdines** [comment]
@Aramgutang it looks like you fixed this issue; can you please confirm

**Comment by Aramgutang** [comment]
Yes, in @ac78ff98bdf838, pretty sure everything worked as part of a bigger project after that.
